name: plantist
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_core: ^2.31.0
  firebase_auth: ^4.19.5
  get: ^4.6.6
  flutter_sfsymbols: ^2.0.0
  cloud_firestore: ^4.17.3
  flutter_cupertino_date_picker_fork: ^1.0.7
  intl: ^0.19.0
  image_picker: ^1.1.1
  firebase_storage: ^11.7.5
  local_auth: ^2.1.4
  get_storage: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/plantist_logo.png
  
  fonts:
    - family: SanFrancisco
      fonts:
        - asset: assets/fonts/SFProText-Regular.ttf
        - asset: assets/fonts/SFProText-Bold.ttf
          weight: 700
